fix: Restructure for future enhancements
These changes will make it easier to add custom commands in the future.

diff --git a/dotfiles b/dotfiles
--- a/dotfiles
+++ b/dotfiles
@@ -3,6 +3,7 @@
 DOTFILES_GIT_PATH=${DOTFILES_GIT_PATH:-git}
 DOTFILES_DIR=${DOTFILES_DIR:-"$HOME/dotfiles"}
 DOTFILES_DATE_FORMAT=${DOTFILES_DATE_FORMAT:-"%Y-%m-%d %H:%M:%S"}
+DOTFILES_PAGER=${DOTFILES_PAGER:-less}
 
 set -o nounset
 
@@ -36,35 +37,44 @@ _dotfiles() {
   ${_exec:-} "$DOTFILES_GIT_PATH" --git-dir="$DOTFILES_DIR" --work-tree="$HOME" "$@"
 }
 
-if ! [[ -d "$DOTFILES_DIR" ]]; then
-  if [[ "${1:-}" == init ]]; then
-    url=${2:-${DOTFILES_REPOSITORY_URL}}
-    if [[ -n "$url" ]]; then
-      log_info "cloning dotfiles directory \"$DOTFILES_DIR\" from \"$url\""
-      tmpdir=$(mktemp -d "$HOME/.dotfiles.tmpXXXXXX")
-      trap 'rm -rf "$tmpdir"' EXIT
+init_dotfiles_dir() {
+  if [[ -d "$DOTFILES_DIR" ]]; then
+    log_info "dotfiles dir \"$DOTFILES_DIR\" already exists"
+    exit
+  fi
 
-      # By cloning with --separate-git-dir into a temporary directory (and
-      # deleting the temporary directory) instead of using --bare, we get
-      # git to set up the remote branch configuration for us.
-      git clone "$url" --separate-git-dir "$DOTFILES_DIR" "$tmpdir" ||
-        die "failed to clone dotfiles directory from \"$url\""
-      rm -rf "$tmpdir"
+  url=${1:-${DOTFILES_REPOSITORY_URL}}
+  if [[ -n "$url" ]]; then
+    log_info "cloning dotfiles directory \"$DOTFILES_DIR\" from \"$url\""
+    tmpdir=$(mktemp -d "$HOME/.dotfiles.tmpXXXXXX")
+    trap 'rm -rf "$tmpdir"' EXIT
 
-      _dotfiles config --local core.worktree "$HOME" ||
-        die "failed to configure dotfiles directory"
-    else
-      log_info "creating dotfiles directory \"$DOTFILES_DIR\""
-      git init --bare "$DOTFILES_DIR" ||
-        die "failed to initialize dotfiles directory \"$DOTFILES_DIR\""
-    fi
+    # By cloning with --separate-git-dir into a temporary directory (and
+    # deleting the temporary directory) instead of using --bare, we get
+    # git to set up the remote branch configuration for us.
+    git clone "$url" --separate-git-dir "$DOTFILES_DIR" "$tmpdir" ||
+      die "failed to clone dotfiles directory from \"$url\""
+    rm -rf "$tmpdir"
 
-    # Don't show untracked files by default (because there will be many of them).
-    _dotfiles config --local status.showUntrackedFiles no ||
+    _dotfiles config --local core.worktree "$HOME" ||
       die "failed to configure dotfiles directory"
   else
-    die "no dotfiles directory (use 'dotfiles init' to create one)"
+    log_info "creating dotfiles directory \"$DOTFILES_DIR\""
+    git init --bare "$DOTFILES_DIR" ||
+      die "failed to initialize dotfiles directory \"$DOTFILES_DIR\""
   fi
-fi
+
+  # Don't show untracked files by default (because there will be many of them).
+  _dotfiles config --local status.showUntrackedFiles no ||
+    die "failed to configure dotfiles directory"
+}
+
+case "$1" in
+init)
+  shift
+  init_dotfiles_dir "$@"
+  exit
+  ;;
+esac
 
 _exec="exec" _dotfiles "$@"
